language: java
jdk:
- oraclejdk8

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn clean test

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - leo114000@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
